-- ============================================================
-- NEXUS — initial schema
-- Postgres + pgvector. Content tables drive both the site and
-- the RAG knowledge base. Embedding dim = 768 (Gemini text-embedding-004).
-- ============================================================

create extension if not exists vector;
create extension if not exists pg_trgm;

-- ── helper: auto-update updated_at ──────────────────────────
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── profile (single row) ────────────────────────────────────
create table if not exists profile (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  headline      text,
  bio           text,
  location      text,
  avatar_url    text,
  socials       jsonb not null default '{}',
  system_prompt text,
  updated_at    timestamptz not null default now()
);
create trigger trg_profile_updated before update on profile
  for each row execute function set_updated_at();

-- ── projects ────────────────────────────────────────────────
create table if not exists projects (
  id              uuid primary key default gen_random_uuid(),
  slug            text unique not null,
  title           text not null,
  summary         text,
  description_md  text,
  hero_image_url  text,
  live_url        text,
  repo_url        text,
  tech_stack      text[] not null default '{}',
  category        text,                              -- ai | web | data | tooling
  status          text,                              -- production | wip | hackathon | archived
  complexity      int  default 3,                    -- 1..5
  challenges_md   text,
  learnings_md    text,
  features        jsonb default '[]',
  screenshots     text[] default '{}',
  video_url       text,
  timeline        jsonb default '{}',
  impact_md       text,
  future_md       text,
  enabled         boolean not null default true,
  sort_order      int default 0,
  updated_at      timestamptz not null default now()
);
create index if not exists idx_projects_tech on projects using gin (tech_stack);
create index if not exists idx_projects_enabled on projects (enabled, sort_order);
create trigger trg_projects_updated before update on projects
  for each row execute function set_updated_at();

-- ── skills ──────────────────────────────────────────────────
create table if not exists skills (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  category          text,
  proficiency       int default 3,                   -- 1..5
  years             numeric,
  related_skill_ids uuid[] default '{}',
  icon              text,
  enabled           boolean not null default true,
  sort_order        int default 0
);

-- ── experience ──────────────────────────────────────────────
create table if not exists experience (
  id          uuid primary key default gen_random_uuid(),
  org         text not null,
  role        text not null,
  start_date  date,
  end_date    date,
  summary_md  text,
  type        text,                                  -- internship | job | research
  highlights  text[] default '{}',
  sort_order  int default 0
);

-- ── achievements & certificates ─────────────────────────────
create table if not exists achievements (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  description_md  text,
  date            date,
  url             text,
  category        text
);

create table if not exists certificates (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  issuer          text,
  issue_date      date,
  credential_url  text,
  image_url       text
);

-- ── knowledge base (generated by ingestion, read by RAG) ────
create table if not exists repos (
  id               uuid primary key default gen_random_uuid(),
  full_name        text unique not null,
  description      text,
  language         text,
  topics           text[] default '{}',
  stars            int default 0,
  last_pushed      timestamptz,
  readme_md        text,
  summary_md       text,
  dependency_graph jsonb default '{}',
  enabled          boolean not null default true
);

create table if not exists documents (
  id           uuid primary key default gen_random_uuid(),
  source_type  text not null,                        -- repo_readme | resume | project | skill | experience | blog
  source_ref   text,
  title        text,
  raw_content  text,
  metadata     jsonb default '{}',
  updated_at   timestamptz not null default now()
);
create index if not exists idx_documents_trgm on documents using gin (raw_content gin_trgm_ops);

create table if not exists chunks (
  id           uuid primary key default gen_random_uuid(),
  document_id  uuid references documents(id) on delete cascade,
  content      text not null,
  token_count  int,
  metadata     jsonb default '{}',
  embedding    vector(768)
);
-- Approximate nearest-neighbour index for vector search.
create index if not exists idx_chunks_embedding on chunks
  using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- ── conversations & analytics ───────────────────────────────
create table if not exists conversations (
  id          uuid primary key default gen_random_uuid(),
  visitor_id  text,
  title       text,
  started_at  timestamptz not null default now()
);

create table if not exists messages (
  id               uuid primary key default gen_random_uuid(),
  conversation_id  uuid references conversations(id) on delete cascade,
  role             text not null,
  content_md       text,
  citations        jsonb default '[]',
  confidence       numeric,
  created_at       timestamptz not null default now()
);

create table if not exists events (
  id      uuid primary key default gen_random_uuid(),
  type    text not null,
  payload jsonb default '{}',
  ts      timestamptz not null default now()
);
